#!/bin/bash
# https://github.com/doodleEsc/nvim/blob/master/clipboard-provider
#
# clipboard provider for neovim
#
# :help provider-clipboard

: ${COPY_PROVIDERS:=osc52 pb xclip tmux local}
: ${PASTE_PROVIDERS:=pb xclip tmux local}
: ${TTY:=`(tty || tmux display-message -p '#{pane_tty}') 2>/dev/null | grep /dev/`}

LOCAL_STORAGE=$HOME/.clipboard-provider.out

main() {
    case $1 in
        copy)
            buffer=$(base64 | tr -d '\n')
            for p in $COPY_PROVIDERS; do
                if $p-provider copy; then exit 0; fi
            done ;;
        paste)
            for p in $PASTE_PROVIDERS; do
                if $p-provider paste; then exit 0; fi
            done ;;
    esac
    exit 1
}

tmux-provider() {
    [[ -n $TMUX ]] || return 1
    case $1 in
        copy) base64 --decode <<<"$buffer" | tmux load-buffer - ;;
        paste) tmux save-buffer - ;;
    esac
}

pb-provider() {
    command -v pbcopy &>/dev/null || return 1
    case $1 in
        copy) base64 --decode <<<"$buffer" | pbcopy ;;
        paste) pbpaste ;;
    esac
}

osc52-provider() {
    [[ -n "$TTY" ]] || return 1
    case $1 in
        copy) printf $'\e]52;c;%s\a' "$buffer" > "$TTY" ;;
        paste) return 1 ;;
    esac
}

local-provider() {
    case $1 in
        copy) base64 --decode <<<"$buffer" > $LOCAL_STORAGE ;;
        paste) cat $LOCAL_STORAGE ;;
    esac
}

xclip-provider() {
    [[ -n $DISPLAY ]] && command -v xclip &>/dev/null || return 1
    case $1 in
        copy) base64 --decode <<<"$buffer" | xclip -i -selection clipboard;;
        paste) xclip -o -selection clipboard;;
    esac
}

main "$@"
